version: '3.8'
services:
  postgres:
    image: postgres:16.2
    container_name: BD
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: benja
      POSTGRES_DB: ProyectoUtec
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: